### ISSUE TITLE
Control panel sometimes empty

### ISSUE THREAD

**Issue by hamoid** [mingness/alternativesoundtrack#17]
```
Exception in thread "Animation Thread" java.util.ConcurrentModificationException
    at java.util.Vector$Itr.checkForComodification(Vector.java:1184)
    at java.util.Vector$Itr.next(Vector.java:1137)
    at controlP5.ControllerGroup.drawControllers(Unknown Source)
    at controlP5.ControllerGroup.draw(Unknown Source)
    at controlP5.ControlWindow.draw(Unknown Source)
    at controlP5.ControlWindow.draw(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1395)
    at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1388)
    at processing.core.PApplet.handleMethods(PApplet.java:1582)
    at processing.core.PApplet.handleDraw(PApplet.java:2411)
    at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1523)
    at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

**Comment by hamoid** [comment]
Others with the same error:

https://forum.processing.org/one/topic/controlp5-and-java-util-concurrentmodificationexception.html

**Comment by damianfallas** [comment]
I found that this work:

noLoop();
//ControlP5 add removes components
loop();
